services:
  - type: web
    name: sendit-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install && npx prisma generate
    startCommand: cd Backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false 